version: '3.7'
services:
    app-client:
        container_name: client
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
