version: '3.4'
services:
  app:
    build:
      dockerfile: ./docker/go.Dockerfile
      context: .
    image: alexzephiros/amarlinda-api:latest
    container_name: server
    volumes:
      - .:/amarlinda
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - prod
    depends_on:
      - "mysql"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '${DB_PORT_INTERNAL}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
    volumes:
      - ./mysql:/var/lib/mysql
    volumes:
      - ./docker/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - prod

networks:
  prod:
    driver: bridge
