version: '3.4'
services:
  app:
    build:
      dockerfile: ./docker/go.Dockerfile
      context: .
    image: golang
    container_name: app
    volumes:
      - .:/amarlinda
    ports:
      - 8082:8080
    networks:
      - prod
    depends_on:
      - "mysql"
      - "redis"

  redis:
    image: redis
    container_name: redis
    networks:
      - prod
    depends_on:
      - mysql
    expose:
      - '6379'

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'amarlinda'
    volumes:
      - ./mysql:/var/lib/mysql
    volumes:
      - ./docker/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - prod

networks:
  prod:
    driver: bridge
